

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Tiger@1234
      MYSQL_DATABASE: threats_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/threats_db.sql:/docker-entrypoint-initdb.d/threats_db.sql

  backend:
    build: ./backend
    container_name: backend_app
    restart: always
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql_db
      DB_USER: root
      DB_PASS: Tiger@1234
      DB_NAME: threats_db
      JWT_SECRET: manju
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: frontend_app
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db_data:
